apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-agent
  namespace: grafana-agent
spec:
  selector:
    matchLabels:
      name: grafana-agent
  template:
    metadata:
      labels:
        name: grafana-agent
    spec:
      serviceAccountName: grafana-agent
      containers:
        - name: grafana-agent
          image: grafana/agent:v0.30.0
          args:
            - "--config.file=/etc/agent/agent.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/agent
            - name: varlog
              mountPath: /var/log
            - name: positions
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: grafana-agent-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: positions
          emptyDir: {}
