apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend
